# Root-level wrangler.toml for Cloudflare Pages deployment
name = "cruiser-aviation-frontend"
main = "packages/frontend/src/worker.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "packages/frontend/dist"

[build]
command = "cd packages/frontend && npm run build"
cwd = "packages/frontend"

# Import the environment configurations from the frontend package
[env.production]
name = "cruiser-aviation-frontend"
main = "packages/frontend/src/worker.ts"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cruiser-db-prod"
database_id = "f10d38b010894c3a8e75c77d2b0ae6a9"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-prod"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "f10d38b010894c3a8e75c77d2b0ae6a9"

[[env.production.kv_namespaces]]
binding = "STATIC_CONTENT"
id = "f810882156314ae6962a4523d719327c"

[env.production.vars]
VITE_API_URL = "https://api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"

[env.production.observability.logs]
enabled = false

[env.production.triggers]
crons = []

[env.staging]
name = "cruiser-aviation-frontend-staging"
main = "packages/frontend/src/worker.ts"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "cruiser-db-staging"
database_id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-staging"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.staging.kv_namespaces]]
binding = "STATIC_CONTENT"
id = "bd25319670d844718fbae8ac0656e132"

[env.staging.vars]
VITE_API_URL = "https://staging-api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "staging"
VITE_DEBUG = "true"

[env.staging.observability.logs]
enabled = false

[env.staging.triggers]
crons = []

[observability.logs]
enabled = false

[triggers]
crons = [] 