# Root-level wrangler.toml for Cloudflare Workers deployment
name = "cruiser-aviation-app"
main = "packages/frontend/src/worker.ts"
compatibility_date = "2025-07-05"

# Build configuration for Workers Sites
[build]
command = "npm run build"
cwd = "packages/frontend"

# Workers Sites configuration
[site]
bucket = "packages/frontend/dist"

# Default environment variables (used by Cloudflare Workers)
[vars]
VITE_API_URL = "https://api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"
VITE_CLOUDFLARE_ACCESS_AUD = "https://app.cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

# API Worker Configuration
[env.api]
name = "cruiser-aviation-api"
main = "packages/backend/src/worker-api.ts"
compatibility_date = "2025-07-05"

[[env.api.d1_databases]]
binding = "DB"
database_name = "cruiser-db-prod"
database_id = "4e925626-5ce3-4f0a-ad1b-e38a45068d5e"

[[env.api.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-prod"

[[env.api.kv_namespaces]]
binding = "CACHE"
id = "f10d38b010894c3a8e75c77d2b0ae6a9"

[env.api.vars]
JWT_SECRET = "your-jwt-secret-here"
CLOUDFLARE_ACCESS_AUD = "https://app.cruiseraviation.com"

# API Staging Environment
[env.api-staging]
name = "cruiser-aviation-api-staging"
main = "packages/backend/src/worker-api.ts"
compatibility_date = "2025-07-05"

[[env.api-staging.d1_databases]]
binding = "DB"
database_name = "cruiser-db-staging"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.api-staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-staging"

[[env.api-staging.kv_namespaces]]
binding = "CACHE"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[env.api-staging.vars]
JWT_SECRET = "your-jwt-secret-here"
CLOUDFLARE_ACCESS_AUD = "https://staging.cruiseraviation.com"

# Production environment (default)
[env.production]
name = "cruiser-aviation-app"
main = "packages/frontend/src/worker.ts"
compatibility_date = "2025-07-05"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cruiser-db-prod"
database_id = "4e925626-5ce3-4f0a-ad1b-e38a45068d5e"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-prod"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "f10d38b010894c3a8e75c77d2b0ae6a9"

[[env.production.kv_namespaces]]
binding = "STATIC_CONTENT"
id = "f810882156314ae6962a4523d719327c"

[env.production.vars]
VITE_API_URL = "https://api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"
VITE_CLOUDFLARE_ACCESS_AUD = "https://app.cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

[env.production.observability.logs]
enabled = false

[env.production.triggers]
crons = []

# Staging environment
[env.staging]
name = "cruiser-aviation-frontend-staging"
main = "packages/frontend/src/worker.ts"
compatibility_date = "2025-07-05"

[[env.staging.d1_databases]]
binding = "DB_STAGING"
database_name = "cruiser-db-staging"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.staging.r2_buckets]]
binding = "STORAGE_STAGING"
bucket_name = "cruiser-storage-staging"

[[env.staging.kv_namespaces]]
binding = "CACHE_STAGING"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.staging.kv_namespaces]]
binding = "STATIC_CONTENT_STAGING"
id = "169a44fd52ec4d9d885a44ecba941dc4"

[env.staging.vars]
VITE_API_URL = "https://staging-api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation (Staging)"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "staging"
VITE_DEBUG = "true"
VITE_CLOUDFLARE_ACCESS_AUD = "https://staging.cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

[env.staging.observability.logs]
enabled = false

[env.staging.triggers]
crons = []

# Local development environment
[env.local]
name = "cruiser-aviation-frontend-local"
main = "packages/frontend/src/worker.ts"
compatibility_date = "2025-07-05"

[[env.local.d1_databases]]
binding = "DB_LOCAL"
database_name = "cruiser-db-staging"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.local.r2_buckets]]
binding = "STORAGE_LOCAL"
bucket_name = "cruiser-storage-staging"

[[env.local.kv_namespaces]]
binding = "CACHE_LOCAL"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.local.kv_namespaces]]
binding = "STATIC_CONTENT_LOCAL"
id = "cde2db60fa8947d79a44b0869a5f8995"

[env.local.vars]
VITE_API_URL = "http://localhost:8787"
VITE_APP_NAME = "Cruiser Aviation (Local)"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "local"
VITE_DEBUG = "true"
VITE_CLOUDFLARE_ACCESS_AUD = ""
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = ""

[env.local.observability.logs]
enabled = false

[env.local.triggers]
crons = []

[observability.logs]
enabled = false

[triggers]
crons = [] 