// Mock data for staging and production environments
export const mockData = {
  services: [
    { 
      id: 1, 
      name: 'Flight Training', 
      description: 'Professional flight instruction',
      type: 'instruction',
      basePrice: 150,
      duration: '1 hour',
      defaultPaymentPlan: 'full_payment',
      isActive: true,
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=='
    },
    { 
      id: 2, 
      name: 'Aircraft Rental', 
      description: 'Hourly aircraft rental',
      type: 'aircraft_rental',
      basePrice: 200,
      duration: '1 hour',
      defaultPaymentPlan: 'full_payment',
      isActive: true,
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=='
    },
    { 
      id: 3, 
      name: 'Maintenance', 
      description: 'Aircraft maintenance services',
      type: 'instruction',
      basePrice: 100,
      duration: '1 hour',
      defaultPaymentPlan: 'full_price',
      isActive: true,
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=='
    }
  ],
  bases: [
    { 
      id: 1, 
      name: 'Main Airport', 
      location: 'Downtown', 
      code: 'MAIN',
      description: 'Primary airport facility',
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
      isActive: true
    },
    { 
      id: 2, 
      name: 'Regional Field', 
      location: 'Suburbs', 
      code: 'REG',
      description: 'Secondary regional facility',
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
      isActive: true
    }
  ],
  aircraft: [
    { 
      id: 1, 
      name: 'Cessna 172', 
      type: 'Single Engine', 
      registration: 'N12345',
      call_sign: 'N12345',
      model: 'Cessna 172 Skyhawk',
      year: 2015,
      total_time: 1200,
      isActive: true,
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=='
    },
    { 
      id: 2, 
      name: 'Piper Arrow', 
      type: 'Single Engine', 
      registration: 'N67890',
      call_sign: 'N67890',
      model: 'Piper PA-28R-201 Arrow',
      year: 2018,
      total_time: 800,
      isActive: true,
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=='
    }
  ],
  users: [
    { 
      id: 1, 
      email: 'admin@cruiser.com', 
      firstName: 'Admin',
      lastName: 'User',
      name: 'Admin User', 
      role: 'admin',
      status: 'active',
      phoneNumber: '+1 (555) 111-1111',
      createdAt: '2024-01-01T00:00:00Z',
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
      address: '123 Admin St',
      city: 'Admin City',
      region: 'Admin Region',
      country: 'USA',
      postalCode: '12345',
      nationality: 'American',
      dateOfBirth: '1980-01-01T00:00:00Z',
      nationalId: 'ADMIN123',
      sex: 'M',
      hasPPL: true,
      pplNumber: 'PPL123456',
      pplIssueDate: '2020-01-01T00:00:00Z',
      pplExpiryDate: '2030-01-01T00:00:00Z',
      medicalCertificateNumber: 'MED123456',
      medicalExamDate: '2023-01-01T00:00:00Z',
      medicalIssueDate: '2023-01-01T00:00:00Z',
      medicalExpiryDate: '2025-01-01T00:00:00Z',
      totalFlightHours: 1000,
      creditedHours: 950
    },
    { 
      id: 2, 
      email: 'pilot@cruiser.com', 
      firstName: 'Pilot',
      lastName: 'User',
      name: 'Pilot User', 
      role: 'pilot',
      status: 'active',
      phoneNumber: '+1 (555) 222-2222',
      createdAt: '2024-01-15T00:00:00Z',
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
      address: '456 Pilot Ave',
      city: 'Pilot City',
      region: 'Pilot Region',
      country: 'USA',
      postalCode: '67890',
      nationality: 'American',
      dateOfBirth: '1985-05-15T00:00:00Z',
      nationalId: 'PILOT456',
      sex: 'F',
      hasPPL: true,
      pplNumber: 'PPL789012',
      pplIssueDate: '2021-06-01T00:00:00Z',
      pplExpiryDate: '2031-06-01T00:00:00Z',
      medicalCertificateNumber: 'MED789012',
      medicalExamDate: '2023-06-01T00:00:00Z',
      medicalIssueDate: '2023-06-01T00:00:00Z',
      medicalExpiryDate: '2025-06-01T00:00:00Z',
      totalFlightHours: 500,
      creditedHours: 480
    },
    {
      id: 3,
      email: 'student@cruiser.com',
      firstName: 'Student',
      lastName: 'Pilot',
      name: 'Student Pilot',
      role: 'student_pilot',
      status: 'pending',
      phoneNumber: '+1 (555) 333-3333',
      createdAt: '2024-01-20T00:00:00Z',
      imageUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
      address: '789 Student Blvd',
      city: 'Student City',
      region: 'Student Region',
      country: 'USA',
      postalCode: '11111',
      nationality: 'American',
      dateOfBirth: '1995-12-10T00:00:00Z',
      nationalId: 'STUDENT789',
      sex: 'M',
      hasPPL: false,
      pplNumber: '',
      pplIssueDate: null,
      pplExpiryDate: null,
      medicalCertificateNumber: 'MED345678',
      medicalExamDate: '2024-01-01T00:00:00Z',
      medicalIssueDate: '2024-01-01T00:00:00Z',
      medicalExpiryDate: '2026-01-01T00:00:00Z',
      totalFlightHours: 25,
      creditedHours: 20
    }
  ]
}; 