name = "cruiser-aviation-frontend"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "cruiser-aviation-frontend"

[env.staging]
name = "cruiser-aviation-frontend-staging"

# Environment variables for the worker
[[env.production.vars]]
name = "VITE_API_URL"
value = "https://api.cruiseraviation.com"

[[env.production.vars]]
name = "VITE_APP_NAME"
value = "Cruiser Aviation"

[[env.production.vars]]
name = "VITE_APP_VERSION"
value = "1.0.0"

[[env.production.vars]]
name = "VITE_FIREBASE_API_KEY"
value = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"

[[env.production.vars]]
name = "VITE_FIREBASE_AUTH_DOMAIN"
value = "cruiserapp-b8429.firebaseapp.com"

[[env.production.vars]]
name = "VITE_FIREBASE_PROJECT_ID"
value = "cruiserapp-b8429"

[[env.production.vars]]
name = "VITE_FIREBASE_STORAGE_BUCKET"
value = "cruiserapp-b8429.firebasestorage.app"

[[env.production.vars]]
name = "VITE_FIREBASE_MESSAGING_SENDER_ID"
value = "443919130210"

[[env.production.vars]]
name = "VITE_FIREBASE_APP_ID"
value = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"

[[env.production.vars]]
name = "VITE_FIREBASE_MEASUREMENT_ID"
value = "G-BCDHQJ67Z0"

[[env.staging.vars]]
name = "VITE_API_URL"
value = "https://staging-api.cruiseraviation.com"

[[env.staging.vars]]
name = "VITE_APP_NAME"
value = "Cruiser Aviation (Staging)"

[[env.staging.vars]]
name = "VITE_APP_VERSION"
value = "1.0.0"

[[env.staging.vars]]
name = "VITE_FIREBASE_API_KEY"
value = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"

[[env.staging.vars]]
name = "VITE_FIREBASE_AUTH_DOMAIN"
value = "cruiserapp-b8429.firebaseapp.com"

[[env.staging.vars]]
name = "VITE_FIREBASE_PROJECT_ID"
value = "cruiserapp-b8429"

[[env.staging.vars]]
name = "VITE_FIREBASE_STORAGE_BUCKET"
value = "cruiserapp-b8429.firebasestorage.app"

[[env.staging.vars]]
name = "VITE_FIREBASE_MESSAGING_SENDER_ID"
value = "443919130210"

[[env.staging.vars]]
name = "VITE_FIREBASE_APP_ID"
value = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"

[[env.staging.vars]]
name = "VITE_FIREBASE_MEASUREMENT_ID"
value = "G-BCDHQJ67Z0"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Static assets configuration
[site]
bucket = "./dist" 