name = "cruiser-aviation-frontend"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "cruiser-aviation-frontend"

[env.staging]
name = "cruiser-aviation-frontend-staging"

[env.preview]
name = "cruiser-aviation-frontend-preview" 