main = "src/worker.ts"
name = "cruiser-aviation-frontend"
compatibility_date = "2024-01-01"

[env.production]
name = "cruiser-aviation-frontend"
main = "src/worker.ts"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cruiser-db-prod"
database_id = "6f01752f-dcac-45fb-a313-aca93c9edad0"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-prod"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "f10d38b010894c3a8e75c77d2b0ae6a9"

[[env.production.kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "f10d38b010894c3a8e75c77d2b0ae6a9"

# Cloudflare Access JWT secret (you'll need to get this from your Cloudflare dashboard)
[env.production.secrets]
JWT_SECRET = "your-cloudflare-access-jwt-secret-here"

# Example production vars (add more as needed)
[env.production.vars]
VITE_API_URL = "https://api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"
VITE_FIREBASE_API_KEY = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"
VITE_FIREBASE_AUTH_DOMAIN = "cruiserapp-b8429.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "cruiserapp-b8429"
VITE_FIREBASE_STORAGE_BUCKET = "cruiserapp-b8429.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "443919130210"
VITE_FIREBASE_APP_ID = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"
VITE_FIREBASE_MEASUREMENT_ID = "G-BCDHQJ67Z0"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"

# Cloudflare Access configuration
VITE_CLOUDFLARE_ACCESS_AUD = "https://cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

[env.staging]
name = "cruiser-aviation-frontend-staging"
main = "src/worker.ts"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "cruiser-db-staging"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-staging"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.staging.kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

# Cloudflare Access JWT secret (you'll need to get this from your Cloudflare dashboard)
[env.staging.secrets]
JWT_SECRET = "your-cloudflare-access-jwt-secret-here"

# Example staging vars (add more as needed)
[env.staging.vars]
VITE_API_URL = "https://staging-api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation (Staging)"
VITE_APP_VERSION = "1.0.0"
VITE_FIREBASE_API_KEY = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"
VITE_FIREBASE_AUTH_DOMAIN = "cruiserapp-b8429.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "cruiserapp-b8429"
VITE_FIREBASE_STORAGE_BUCKET = "cruiserapp-b8429.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "443919130210"
VITE_FIREBASE_APP_ID = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"
VITE_FIREBASE_MEASUREMENT_ID = "G-BCDHQJ67Z0"
VITE_ENVIRONMENT = "staging"
VITE_DEBUG = "true"

# Cloudflare Access configuration
VITE_CLOUDFLARE_ACCESS_AUD = "https://staging.cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

[build]
command = "npm run build"
cwd = "."

[env.local]
name = "cruiser-aviation-frontend-local"
main = "src/worker.ts"

[[env.local.d1_databases]]
binding = "DB"
database_name = "cruiser-db-staging"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.local.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-staging"

[[env.local.kv_namespaces]]
binding = "CACHE"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.local.kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

# Cloudflare Access JWT secret (disabled for local development)
[env.local.secrets]
JWT_SECRET = "local-development-secret"

# Local development vars
[env.local.vars]
VITE_API_URL = "http://localhost:8787"
VITE_APP_NAME = "Cruiser Aviation (Local)"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "local"
VITE_DEBUG = "true"
VITE_FIREBASE_API_KEY = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"
VITE_FIREBASE_AUTH_DOMAIN = "cruiserapp-b8429.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "cruiserapp-b8429"
VITE_FIREBASE_STORAGE_BUCKET = "cruiserapp-b8429.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "443919130210"
VITE_FIREBASE_APP_ID = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"
VITE_FIREBASE_MEASUREMENT_ID = "G-BCDHQJ67Z0"

# Cloudflare Access configuration (disabled for local development)
VITE_CLOUDFLARE_ACCESS_AUD = ""
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = ""

[site]
bucket = "./dist" 