name = "cruiser-aviation-frontend"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "cruiser-aviation-frontend"

[env.staging]
name = "cruiser-aviation-frontend-staging"

# Environment variables for the worker
[[env.production.vars]]
name = "VITE_API_URL"
value = "https://your-backend-api.com"

[[env.production.vars]]
name = "VITE_APP_NAME"
value = "Cruiser Aviation"

[[env.production.vars]]
name = "VITE_APP_VERSION"
value = "1.0.0"

[[env.staging.vars]]
name = "VITE_API_URL"
value = "https://your-staging-api.com"

[[env.staging.vars]]
name = "VITE_APP_NAME"
value = "Cruiser Aviation (Staging)"

[[env.staging.vars]]
name = "VITE_APP_VERSION"
value = "1.0.0"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Static assets configuration
[site]
bucket = "./dist"
entry-point = "workers-site" 