[build]
command = "npm run build"
cwd = "."

[env.production]
name = "cruiser-aviation-frontend"
compatibility_date = "2024-01-01"

[env.staging]
name = "cruiser-aviation-frontend-staging"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"

# Build settings
[build.upload]
format = "directory" 