# Main configuration (production by default)
main = "src/worker.ts"
name = "cruiser-aviation-frontend"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = false

[triggers]
crons = []

[build]
command = "npm run build"
cwd = "."

# Production environment (default)
[[d1_databases]]
binding = "DB"
database_name = "cruiser-db-prod"
database_id = "6f01752f-dcac-45fb-a313-aca93c9edad0"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-prod"

[[kv_namespaces]]
binding = "CACHE"
id = "f10d38b010894c3a8e75c77d2b0ae6a9"

[[kv_namespaces]]
binding = "STATIC_CONTENT"
id = "679667a04c0b4beeb88579cbeacce07e"

[vars]
VITE_API_URL = "https://api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation"
VITE_APP_VERSION = "1.0.0"
VITE_FIREBASE_API_KEY = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"
VITE_FIREBASE_AUTH_DOMAIN = "cruiserapp-b8429.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "cruiserapp-b8429"
VITE_FIREBASE_STORAGE_BUCKET = "cruiserapp-b8429.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "443919130210"
VITE_FIREBASE_APP_ID = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"
VITE_FIREBASE_MEASUREMENT_ID = "G-BCDHQJ67Z0"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"
VITE_CLOUDFLARE_ACCESS_AUD = "https://cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

# Staging environment
[env.staging]
name = "cruiser-aviation-frontend-staging"
main = "src/worker.ts"

[env.staging.observability.logs]
enabled = false

[env.staging.triggers]
crons = []

[env.staging.build]
command = "npm run build"
cwd = "."

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.staging.kv_namespaces]]
binding = "STATIC_CONTENT"
id = "169a44fd52ec4d9d885a44ecba941dc4"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "DB_STAGING"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-staging"

[env.staging.vars]
VITE_API_URL = "https://staging-api.cruiseraviation.com"
VITE_APP_NAME = "Cruiser Aviation (Staging)"
VITE_APP_VERSION = "1.0.0"
VITE_FIREBASE_API_KEY = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"
VITE_FIREBASE_AUTH_DOMAIN = "cruiserapp-b8429.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "cruiserapp-b8429"
VITE_FIREBASE_STORAGE_BUCKET = "cruiserapp-b8429.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "443919130210"
VITE_FIREBASE_APP_ID = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"
VITE_FIREBASE_MEASUREMENT_ID = "G-BCDHQJ67Z0"
VITE_ENVIRONMENT = "staging"
VITE_DEBUG = "true"
VITE_CLOUDFLARE_ACCESS_AUD = "https://staging.cruiseraviation.com"
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "cruiseraviation.com"

# Local development environment
[env.local]
name = "cruiser-aviation-frontend-local"
main = "src/worker.ts"

[env.local.observability.logs]
enabled = false

[env.local.triggers]
crons = []

[env.local.build]
command = "npm run build"
cwd = "."

[[env.local.d1_databases]]
binding = "DB"
database_name = "cruiser-db-staging"
database_id = "73665fa6-b020-45ba-899c-e495344a4ee3"

[[env.local.r2_buckets]]
binding = "STORAGE"
bucket_name = "cruiser-storage-staging"

[[env.local.kv_namespaces]]
binding = "CACHE"
id = "b9b4a8aa1da64f3696c4778e03642cb8"

[[env.local.kv_namespaces]]
binding = "STATIC_CONTENT"
id = "cde2db60fa8947d79a44b0869a5f8995"

[env.local.vars]
VITE_API_URL = "http://localhost:8787"
VITE_APP_NAME = "Cruiser Aviation (Local)"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "local"
VITE_DEBUG = "true"
VITE_FIREBASE_API_KEY = "AIzaSyChijXhZBr7ycWKEQSK1bCdLSoQioKEurk"
VITE_FIREBASE_AUTH_DOMAIN = "cruiserapp-b8429.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "cruiserapp-b8429"
VITE_FIREBASE_STORAGE_BUCKET = "cruiserapp-b8429.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "443919130210"
VITE_FIREBASE_APP_ID = "1:443919130210:web:b8a009ef9ca1ca4f433b3b"
VITE_FIREBASE_MEASUREMENT_ID = "G-BCDHQJ67Z0"
VITE_CLOUDFLARE_ACCESS_AUD = ""
VITE_CLOUDFLARE_ACCESS_TEAM_DOMAIN = ""

# Site configuration for static assets
[site]
bucket = "./dist" 