name: Deploy to Cloudflare Workers

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        working-directory: packages/frontend
        run: npm ci

      - name: Build application
        working-directory: packages/frontend
        run: npm run build

      - name: Deploy to Cloudflare Workers
        working-directory: packages/frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "Deploying to production..."
            npx wrangler deploy --env production
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "Deploying to staging..."
            npx wrangler deploy --env staging
          else
            echo "Branch ${{ github.ref }} - no deployment"
          fi

      - name: Comment PR with deployment info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const environment = '${{ github.ref }}' === 'refs/heads/master' ? 'production' : 'staging';
            const url = environment === 'production' 
              ? 'https://cruiser-aviation-frontend.julian-pad.workers.dev'
              : 'https://cruiser-aviation-frontend-staging.julian-pad.workers.dev';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Deployment Complete!**
              
              **Environment:** ${environment}
              **URL:** ${url}
              **Branch:** ${{ github.ref_name }}
              
              Your changes have been deployed successfully!`
            }); 