name: Preview Deployment

on:
  pull_request:
    branches: [master, dev]

env:
  NODE_VERSION: '20'

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        working-directory: packages/frontend
        run: npm ci

      - name: Build application
        working-directory: packages/frontend
        run: npm run build

      - name: Deploy preview to Cloudflare Workers
        working-directory: packages/frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Create a unique preview name based on PR number and branch
          PREVIEW_NAME="cruiser-aviation-frontend-preview-pr-${{ github.event.number }}"
          
          echo "Deploying preview: $PREVIEW_NAME"
          
          # Deploy with a unique name for this PR
          npx wrangler deploy --name "$PREVIEW_NAME" --env staging

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://cruiser-aviation-frontend-preview-pr-${{ github.event.number }}.julian-pad.workers.dev`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔍 **Preview Deployment Ready!**
              
              **Preview URL:** ${previewUrl}
              **Branch:** ${{ github.head_ref }}
              **PR:** #${{ github.event.number }}
              
              Your changes are now available for review at the preview URL above!`
            }); 