name: Deploy to Production

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          cd packages/frontend
          npm run build
          
      - name: Generate KV data
        run: |
          cd packages/frontend
          node scripts/upload-kv.js
          
      - name: Upload KV data to production
        run: |
          npx wrangler kv bulk put --binding=STATIC_CONTENT --env production packages/frontend/kv-data.json
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy to Cloudflare Workers Production
        run: |
          npx wrangler@4 deploy --env production
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Notify deployment
        run: |
          echo "✅ Successfully deployed to production environment!"
          echo "🌍 Production URL: https://app.cruiseraviation.com"
          echo "📊 Deployment completed at $(date)" 