name: Deploy to Production

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          cd packages/frontend
          npm run build
          
      - name: Deploy to Cloudflare Workers Production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          workingDirectory: .
          
      - name: Upload KV data for production
        run: |
          cd packages/frontend
          node scripts/upload-kv.js
          cd ../..
          npx wrangler kv:bulk put packages/frontend/kv-data.json --binding=STATIC_CONTENT --env production
          
      - name: Notify deployment
        run: |
          echo "✅ Successfully deployed to production environment!"
          echo "🌍 Production URL: https://app.cruiseraviation.com"
          echo "📊 Deployment completed at $(date)" 