name: Preview Deployment

on:
  pull_request:
    branches: [dev, master]

env:
  NODE_VERSION: '18'

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd packages/frontend
          npm ci

      - name: Build application
        run: |
          cd packages/frontend
          npm run build
        env:
          VITE_API_URL: 'https://staging-api.cruiseraviation.com'
          VITE_APP_NAME: 'Cruiser Aviation (Preview)'
          VITE_APP_VERSION: '1.0.0'
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_ENVIRONMENT: 'preview'
          VITE_DEBUG: 'true'

      - name: Deploy Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env preview
          packageManager: npm
          workingDirectory: packages/frontend

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://cruiser-aviation-frontend-preview-${prNumber}.${context.payload.repository.owner}.workers.dev`;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 **Preview Deployment Ready!**
              
              **Preview URL:** ${previewUrl}
              **Branch:** ${context.payload.pull_request.head.ref}
              
              Your preview deployment is now live! Test your changes before merging.`
            }); 