name: Preview Deployment

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'packages/frontend/**'

env:
  NODE_VERSION: '18'

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: packages/frontend
        run: npm ci

      - name: Build project
        working-directory: packages/frontend
        run: npm run build
        env:
          # Basic environment variables with fallbacks
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://localhost:3001' }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME || 'Cruiser Aviation' }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION || '1.0.0' }}
          # Firebase - optional for now
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY || '' }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN || '' }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID || '' }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET || '' }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID || '' }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID || '' }}
          # Other optional variables
          VITE_VERIFF_PUBLIC_KEY: ${{ secrets.VITE_VERIFF_PUBLIC_KEY || '' }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY || '' }}
          VITE_ANALYTICS_ID: ${{ secrets.VITE_ANALYTICS_ID || '' }}
          VITE_ENABLE_VERIFF: ${{ secrets.VITE_ENABLE_VERIFF || 'false' }}
          VITE_ENABLE_ANALYTICS: ${{ secrets.VITE_ENABLE_ANALYTICS || 'false' }}

      - name: Deploy to Cloudflare Pages (Preview)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cruiser-aviation-frontend
          directory: packages/frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environmentName: preview 